version: '3.8'

services:
  my-node-app:
    build: .
    ports:
      - "4003:4002"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=hackatho15
      # Otras variables de entorno necesarias para tu aplicación
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hackatho15
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql-data:
